"""Orchestrate test data strategy and produce TestSpec + derive_test_data.sh."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from jinja2 import Environment, FileSystemLoader
from rich.console import Console
from rich.panel import Panel
from rich.table import Table

from code_to_module.models import (
    CodeSource,
    ModuleSpec,
    TestCase,
    TestDataSource,
    TestSpec,
)
from code_to_module.standards import Standards
from code_to_module.test_data_derive import DerivationPlan, plan_derivation
from code_to_module.test_data_match import TestDataMatch, match

_DERIVE_TEMPLATES_DIR = Path(__file__).parent / "templates" / "derive_test_data"

_DERIVE_SCRIPT_HEADER = """\
#!/usr/bin/env bash
# Generated by code-to-module
# Run this script ONCE to produce derived test data files.
# IMPORTANT: The generated files must be submitted to nf-core/test-datasets:
#   1. Fork https://github.com/nf-core/test-datasets
#   2. Add files to the modules branch under the appropriate organism directory
#   3. Open a PR against the modules branch
#   4. Ask on the nf-core Slack #test-data channel before submitting
# See: https://nf-co.re/docs/tutorials/tests_and_test_data/test_data#adding-new-test-data
set -euo pipefail
"""


@dataclass
class _ChannelResult:
    channel_name: str
    format_tags: list[str]
    data_match: TestDataMatch | None
    deriv_plan: DerivationPlan | None


def _render_derive_snippet(plan: DerivationPlan) -> str:
    """Render a shell snippet for a derive plan, stripping its shebang line."""
    if plan.template_name is None:
        return ""
    env = Environment(
        loader=FileSystemLoader(str(_DERIVE_TEMPLATES_DIR)),
        keep_trailing_newline=True,
    )
    rendered = env.get_template(plan.template_name).render(**plan.template_vars)
    lines = rendered.splitlines(keepends=True)
    # Remove the shebang — the combined script has its own header
    stripped = [line for line in lines if not line.startswith("#!")]
    return "".join(stripped)


def _print_summary(results: list[_ChannelResult], console: Console) -> None:
    table = Table(title="Test data strategy", show_header=True, header_style="bold")
    table.add_column("Channel")
    table.add_column("Format")
    table.add_column("Strategy")
    table.add_column("Notes")

    for r in results:
        fmt = r.format_tags[0] if r.format_tags else "\u2014"
        if r.data_match is not None:
            strategy = "match"
            notes = f"{r.data_match.id} ({r.data_match.size_kb}KB) \u2014 existing"
        else:
            assert r.deriv_plan is not None
            strategy = r.deriv_plan.strategy
            notes = r.deriv_plan.notes
        table.add_row(r.channel_name, fmt, strategy, notes)

    console.print(table)


def generate_test_spec(
    spec: ModuleSpec,
    source: CodeSource,
    standards: Standards,
    console: Console | None = None,
) -> TestSpec:
    """Orchestrate test data strategy for all input channels.

    Returns a TestSpec with exactly two TestCase objects:
      - real test (is_stub_test=False)
      - always-present stub test (is_stub_test=True)
    """
    if console is None:
        console = Console()

    # Phase 1: resolve each input channel to a strategy
    results: list[_ChannelResult] = []
    for channel in spec.inputs:
        m = match(channel, standards)
        if m is not None:
            results.append(
                _ChannelResult(
                    channel_name=channel.name,
                    format_tags=list(channel.format_tags),
                    data_match=m,
                    deriv_plan=None,
                )
            )
        else:
            plan = plan_derivation(channel, standards, spec.tool_name)
            results.append(
                _ChannelResult(
                    channel_name=channel.name,
                    format_tags=list(channel.format_tags),
                    data_match=None,
                    deriv_plan=plan,
                )
            )

    # Phase 2: collect inputs for both test cases
    real_input_files: list[str] = []
    real_input_sources: list[TestDataSource] = []
    stub_input_files: list[str] = []
    stub_input_sources: list[TestDataSource] = []
    setup_module: str | None = None
    setup_process_name: str | None = None
    setup_input_path: str | None = None
    setup_output_channel: str | None = None
    derived_plans: list[DerivationPlan] = []

    for r in results:
        if r.data_match is not None:
            m = r.data_match
            real_input_files.extend(m.resolved_paths)
            real_input_sources.extend(
                [TestDataSource.NFCORE_DATASETS] * len(m.resolved_paths)
            )
            stub_input_files.extend(m.resolved_paths)
            stub_input_sources.extend(
                [TestDataSource.NFCORE_DATASETS] * len(m.resolved_paths)
            )
        else:
            deriv = r.deriv_plan
            assert deriv is not None
            plan = deriv
            if plan.strategy == "chain":
                setup_module = plan.setup_module
                setup_process_name = plan.setup_process_name
                setup_input_path = plan.setup_input_path
                setup_output_channel = plan.setup_output_channel
                real_input_sources.append(TestDataSource.CHAINED)
            elif plan.strategy == "derive":
                derived_plans.append(plan)
                for f in plan.output_files:
                    real_input_files.append(f"${{projectDir}}/tests/data/{f}")
                    real_input_sources.append(TestDataSource.DERIVED)
            else:  # stub
                real_input_sources.append(TestDataSource.STUB)

    # Phase 3: build derivation script if any DERIVED plans exist
    needs_derivation = bool(derived_plans)
    derivation_script_content: str | None = None
    if needs_derivation:
        parts: list[str] = [_DERIVE_SCRIPT_HEADER]
        for plan in derived_plans:
            snippet = _render_derive_snippet(plan)
            parts.append(f"\n# --- {plan.channel_name} ---\n{snippet}")
        derivation_script_content = "".join(parts)

    # Phase 4: build test cases
    expected_outputs = [ch.name for ch in spec.outputs]

    real_case = TestCase(
        name=f"test_{spec.tool_name}",
        input_files=real_input_files,
        input_sources=real_input_sources,
        setup_module=setup_module,
        setup_module_process_name=setup_process_name,
        setup_module_input=setup_input_path,
        setup_module_output=setup_output_channel,
        expected_outputs=expected_outputs,
        is_stub_test=False,
    )

    stub_case = TestCase(
        name=f"test_{spec.tool_name}_stub",
        input_files=stub_input_files,
        input_sources=stub_input_sources,
        expected_outputs=expected_outputs,
        is_stub_test=True,
    )

    # Phase 5: print summary table and advisory panels
    _print_summary(results, console)

    if needs_derivation:
        console.print(
            Panel(
                "[yellow]Action required: derived test data[/yellow]\n"
                "Run tests/derive_test_data.sh, then PR the output files to nf-core/test-datasets.\n"
                "Always ask on Slack #test-data before submitting new files.",
                border_style="yellow",
            )
        )

    has_stub_channels = any(
        r.deriv_plan is not None and r.deriv_plan.strategy == "stub"
        for r in results
    )
    if has_stub_channels:
        console.print(
            Panel(
                "[blue]Stub mode: some inputs have no available test data[/blue]\n"
                "The module uses Nextflow stub: mode for these channels.\n"
                "See TODO comments in tests/main.nf.test for guidance on adding data later.",
                border_style="blue",
            )
        )

    return TestSpec(
        process_name=spec.process_name,
        test_cases=[real_case, stub_case],
        needs_derivation=needs_derivation,
        derivation_script_content=derivation_script_content,
    )
